  services:
    hello-api:
      image: zadnepr/go-api:latest
      ports:
        - "${APP_PORT}:8080"
      env_file:
        - .env
      volumes:
        - ../api_service:/app  # Привязываем локальный код к контейнеру
        - /app/tmp  # Исключаем сборочные артефакты 
      environment:
        - APP_PORT=8080  # Указываем порт приложения
      command: >
        /app/scripts/wait-for-it.sh postgres:5432 -- 
        bash -c "air"
      restart: always
      depends_on:
        - postgres
      networks:
        - app-network

    postgres:
      image: postgres:15
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "${DB_PORT}:5432"
      volumes:
        - ../../.local_data/postgres:/var/lib/postgresql/data
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge

  volumes:
    postgres-data: