apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 postgres-service 5432; do echo "Waiting for PostgreSQL..."; sleep 5; done;']
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
      containers:
      - name: api
        image: zadnepr/go-api-test:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-env
        volumeMounts:
        - name: project-volume
          mountPath: /app
      volumes:
      - name: project-volume
        hostPath:
          path: /mnt/data  # Путь к каталогу на хосте
          type: Directory